Fix sys/game check in CI

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -71,11 +71,17 @@ jobs:
 
     - name: Check game messages
       run: |
-        errors="$(grep -FA1 'System()' $(grep MsgGame  -lr messages7/) | grep "return true")"
-        [ "$errors" = "" ] || { printf '%s\n' "$errors"; exit 1; }
+        if errors="$(grep -FA1 'System()' $(grep MsgGame  -lr messages7/) | grep "return true")"
+        then
+          printf '%s\n' "$errors"
+          exit 1
+        fi
 
     - name: Check system messages
       run: |
-        errors="$(grep -FA1 'System()' $(grep MsgSys  -lr messages7/) | grep "return false")"
-        [ "$errors" = "" ] || { printf '%s\n' "$errors"; exit 1; }
+        if errors="$(grep -FA1 'System()' $(grep MsgSys  -lr messages7/) | grep "return false")"
+        then
+          printf '%s\n' "$errors"
+          exit 1
+        fi
 
